services:
  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      SECRET_KEY: todo-list-dev-secret

  task_service:
    build:
      context: .
      dockerfile: task_service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      SECRET_KEY: todo-list-dev-secret

  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      SECRET_KEY: todo-list-dev-secret

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ../frontend
    ports:
      - "80:80"
    environment:
      REACT_APP_AUTH_API_URL: http://localhost:8001
      REACT_APP_TASK_API_URL: http://localhost:8002
    depends_on:
      - auth_service
      - task_service
      - user_service

volumes:
  postgres_data:

